### ISSUE TITLE
[FEAT] Speech-To-Text 로직 구현

### ISSUE THREAD

**Issue by ckkim817** [SPARCS-2024-TEAM1/SERVER#9]
## 💡 Issue

- 네이버 클라우드 플랫폼의 Clova Speech를 이용해 음성을 텍스트로 변환해주는 로직을 구현합니다.
- 회원가입/로그인 에러 처리에서 누락된 부분을 추가합니다.

## 📝 To-do
- [x] DTO(Record) 정의
- [x] Repository 인터페이스 생성
- [x] Service 클래스 작성
- [x] Controller 클래스 작성
- [x] 공통 응답 처리 및 예외 처리
- [x] Swagger 테스트
